import {
  BadgePercent,
  Beef,
  Bell,
  Croissant,
  Gift,
  GlassWater,
  Hammer,
  Heart,
  Home,
  LayoutGrid,
  Leaf,
  MapPinned,
  PackageSearch,
  Pill,
  ShieldCheck,
  Shirt,
  ShoppingBasket,
  Sparkles,
  Store,
  Truck,
  UtensilsCrossed,
  Wrench,
  UserRound,
} from 'lucide-react';
import { createElement, type SVGProps } from 'react';

import type {
  HomeCategory,
  HomeFilterGroup,
  HomeFeaturedStore,
  HomeLocation,
  HomeNavItem,
  HomeOffer,
  HomeSponsoredBanner,
  HomeTrustItem,
} from './home.types';

type IconProps = SVGProps<SVGSVGElement> & {
  size?: number;
};

const FastDeliveryIcon = ({ size = 18, ...props }: IconProps) =>
  createElement(
    'svg',
    {
      ...props,
      width: size,
      height: size,
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: 1.8,
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      'aria-hidden': true,
      focusable: false,
    },
    createElement('circle', { cx: 6.2, cy: 17.2, r: 2.05 }),
    createElement('circle', { cx: 16.8, cy: 17.2, r: 2.05 }),
    createElement('path', { d: 'M7.4 17.2h3.2l1.7-3.5h3.2l1.6 2.8' }),
    createElement('path', { d: 'M11.8 13.7l1.1-1.8h2.4l1.1 1.8' }),
    createElement('rect', { x: 14.7, y: 7.7, width: 4, height: 4, rx: 0.9 }),
    createElement('path', { d: 'M4.2 11.3c1.2-.8 2.6-.8 3.8 0' }),
    createElement('path', { d: 'M2.8 8.8c1.1-.6 2.1-.8 3.2-.5' }),
    createElement('path', { d: 'M18.8 9.2h2.1' }),
    createElement('path', { d: 'M17.8 6.8h1.8' }),
  );

export const quickSearches = [
  'coca cola 3L',
  'promo verduras',
  'asado especial',
  'limpieza del hogar',
  'panadería cerca',
];

export const desktopNavItems: HomeNavItem[] = [
  { id: 'home', label: 'Inicio', href: '/', icon: Home },
  { id: 'stores', label: 'Comercios', href: '/comercios', icon: Store },
  { id: 'orders', label: 'Pedidos', href: '/pedidos', icon: PackageSearch },
  { id: 'alerts', label: 'Notificaciones', href: '/notificaciones', icon: Bell },
  { id: 'account', label: 'Cuenta', href: '/mi-cuenta', icon: UserRound },
];

export const mobileNavItems: HomeNavItem[] = [
  { id: 'home', label: 'Inicio', href: '/', icon: Home },
  { id: 'categories', label: 'Categorías', href: '/comercios', icon: LayoutGrid },
  { id: 'orders', label: 'Pedidos', href: '/pedidos', icon: PackageSearch },
  { id: 'favorites', label: 'Favoritos', href: '/favoritos', icon: Heart },
  { id: 'account', label: 'Cuenta', href: '/mi-cuenta', icon: UserRound },
];

export const locations: HomeLocation[] = [
  {
    id: 'centro',
    label: 'La Francia',
    detail: 'Córdoba · entrega rápida en radio corto',
    mapQuery: 'La Francia Córdoba Argentina',
    note: 'Buscamos ofertas, comercios y tiempos desde esta zona.',
  },
  {
    id: 'barrio-norte',
    label: 'Barrio Norte',
    detail: 'Mayor cobertura en comercios de cercanía',
    mapQuery: 'Barrio Norte La Francia Córdoba',
    note: 'Ideal para comparar precios entre tiendas de barrio.',
  },
  {
    id: 'ruta-19',
    label: 'Zona Ruta 19',
    detail: 'Cobertura de mayor distancia y pedidos grandes',
    mapQuery: 'Ruta 19 La Francia Córdoba',
    note: 'Útil para stock más amplio y comercios con delivery extendido.',
  },
];

export const filterGroups: HomeFilterGroup[] = [
  {
    id: 'sort',
    label: 'Ordenar',
    multi: false,
    options: [
      { id: 'featured', label: 'Destacados', description: 'Mayor relevancia y sponsor' },
      { id: 'closest', label: 'Más cercanos', description: 'Primero lo que llega antes' },
      { id: 'cheapest', label: 'Más baratos', description: 'Precio ascendente' },
      { id: 'discount', label: 'Mayor descuento', description: 'Promos y rebajas' },
    ],
  },
  {
    id: 'service',
    label: 'Servicio',
    multi: true,
    options: [
      { id: 'delivery', label: 'Delivery', description: 'Entrega a domicilio' },
      { id: 'pickup', label: 'Retiro', description: 'Retiro en local' },
      { id: 'openNow', label: 'Abierto ahora', description: 'Negocios disponibles ahora' },
    ],
  },
  {
    id: 'distance',
    label: 'Cercanía',
    multi: false,
    options: [
      { id: 'near', label: 'Hasta 1 km', description: 'Entrega muy cercana' },
      { id: 'five', label: 'Hasta 5 km', description: 'Cobertura ampliada' },
      { id: 'twentyFive', label: 'Hasta 25 km', description: 'Cobertura extendida' },
      { id: 'custom', label: 'Personalizado:', description: 'Ingresá un radio entero' },
    ],
  },
];

export const sponsoredBanners: HomeSponsoredBanner[] = [
  {
    id: 'pack-familiar',
    badge: 'OFERTA DESTACADA',
    title: 'Pack familiar',
    subtitle: 'Todo lo que necesitás al mejor precio.',
    store: 'Don José',
    href: '/productos/pack-familiar',
    cta: 'Ver oferta',
    discount: '-20% descuento',
    tone: 'blue',
    imageLabel: 'Familia',
  },
  {
    id: 'frescura-dia',
    badge: 'PATROCINADO',
    title: 'Frescura del día',
    subtitle: 'Frutas y verduras listas para sumar al carrito.',
    store: 'La Huerta',
    href: '/productos/frescura-del-dia',
    cta: 'Explorar',
    discount: '-15% hoy',
    tone: 'green',
    imageLabel: 'Verduras',
  },
  {
    id: 'asado-finde',
    badge: 'OFERTA ESPECIAL',
    title: 'Asado especial',
    subtitle: 'Cortes seleccionados para el finde.',
    store: 'La Estancia',
    href: '/productos/asado-especial',
    cta: 'Ver promo',
    discount: '-10% carne',
    tone: 'red',
    imageLabel: 'Asado',
  },
];

export const categories: HomeCategory[] = [
  { id: 'almacen', name: 'Almacén', description: 'Básicos y reposición diaria', icon: ShoppingBasket, tone: 'blue' },
  { id: 'verduleria', name: 'Verdulería', description: 'Frutas, verduras y combos', icon: Leaf, tone: 'green' },
  { id: 'bebidas', name: 'Bebidas', description: 'Gaseosas, aguas y combos', icon: GlassWater, tone: 'violet' },
  { id: 'carniceria', name: 'Carnicería', description: 'Cortes frescos y pedidos por kilo', icon: Beef, tone: 'red' },
  { id: 'panaderia', name: 'Panadería', description: 'Fresco del día y facturas', icon: Croissant, tone: 'orange' },
  { id: 'kiosco', name: 'Kiosco', description: 'Snacks, bebidas y urgencias', icon: Store, tone: 'slate' },
  { id: 'rotiseria', name: 'Rotisería', description: 'Comidas listas para retirar', icon: UtensilsCrossed, tone: 'gold' },
  { id: 'farmacia', name: 'Farmacia', description: 'Salud, bienestar y perfumería', icon: Pill, tone: 'blue' },
  { id: 'perfumeria', name: 'Perfumería', description: 'Higiene y cuidado personal', icon: Sparkles, tone: 'violet' },
  { id: 'regaleria', name: 'Regalería', description: 'Detalles y decoración', icon: Gift, tone: 'gold' },
  { id: 'ferreteria', name: 'Ferretería', description: 'Herramientas y materiales', icon: Hammer, tone: 'slate' },
  { id: 'indumentaria', name: 'Indumentaria', description: 'Ropa, calzado y accesorios', icon: Shirt, tone: 'blue' },
  { id: 'servicios', name: 'Servicios', description: 'Talleres y asistencia local', icon: Wrench, tone: 'green' },
  { id: 'delivery', name: 'Delivery', description: 'Entrega rápida y seguimiento', icon: Truck, tone: 'red' },
];

export const featuredStores: HomeFeaturedStore[] = [
  {
    id: 'don-jose',
    name: 'Don José',
    category: 'Almacén',
    categoryId: 'almacen',
    logoLabel: 'DJ',
    etaMin: 15,
    etaMax: 25,
    distanceKm: 0.9,
    rating: 4.8,
    delivery: true,
    pickup: true,
    openNow: true,
    tone: 'blue',
    address: 'Av. Principal',
    priceLevel: '$$',
    minOrder: 2000,
    badge: 'Oferta destacada',
    href: '/comercios/almacen-juan',
  },
  {
    id: 'la-huerta',
    name: 'La Huerta',
    category: 'Verdulería',
    categoryId: 'verduleria',
    logoLabel: 'LH',
    etaMin: 20,
    etaMax: 30,
    distanceKm: 1.2,
    rating: 4.9,
    delivery: true,
    pickup: true,
    openNow: true,
    tone: 'green',
    address: 'Centro · La Francia',
    priceLevel: '$',
    minOrder: 1500,
    badge: 'Frescura diaria',
    href: '/comercios/almacen-juan',
  },
  {
    id: 'la-estancia',
    name: 'La Estancia',
    category: 'Carnicería',
    categoryId: 'carniceria',
    logoLabel: 'LE',
    etaMin: 20,
    etaMax: 30,
    distanceKm: 2.1,
    rating: 4.8,
    delivery: true,
    pickup: true,
    openNow: true,
    tone: 'red',
    address: 'Barrio norte',
    priceLevel: '$$$',
    minOrder: 3000,
    badge: 'Asado especial',
    href: '/comercios/carniceria-central',
  },
  {
    id: 'delicias',
    name: 'Delicias',
    category: 'Panadería',
    categoryId: 'panaderia',
    logoLabel: 'DE',
    etaMin: 15,
    etaMax: 20,
    distanceKm: 1.5,
    rating: 4.7,
    delivery: false,
    pickup: true,
    openNow: true,
    tone: 'orange',
    address: 'Sector comercial',
    priceLevel: '$',
    minOrder: 1200,
    badge: 'Recién horneado',
    href: '/comercios/panaderia-la-esquina',
  },
];

export const trustItems: HomeTrustItem[] = [
  {
    id: 'fast',
    title: 'Delivery rápido',
    description: 'Llegamos a tu casa',
    icon: FastDeliveryIcon,
  },
  {
    id: 'local',
    title: 'Comercio local',
    description: 'Apoyá a los negocios de La Francia',
    icon: MapPinned,
  },
  {
    id: 'secure',
    title: 'Pago seguro',
    description: 'Pagá como quieras',
    icon: ShieldCheck,
  },
];

export const nearbyOffers: HomeOffer[] = [
  {
    id: 'banana-premium',
    product: 'Banana premium',
    store: 'La Huerta',
    categoryId: 'verduleria',
    distanceKm: 1.2,
    price: 1700,
    oldPrice: 2000,
    discount: 15,
    delivery: true,
    pickup: true,
    openNow: true,
    tone: 'green',
    imageLabel: 'Bananas',
    href: '/productos/banana-premium',
  },
  {
    id: 'bife-ancho',
    product: 'Bife ancho',
    store: 'La Estancia',
    categoryId: 'carniceria',
    distanceKm: 2.1,
    price: 9900,
    oldPrice: 11000,
    discount: 10,
    delivery: true,
    pickup: true,
    openNow: true,
    tone: 'red',
    imageLabel: 'Carne',
    href: '/productos/bife-ancho',
  },
  {
    id: 'coca-cola-3l',
    product: 'Coca Cola 3L',
    store: 'Don José',
    categoryId: 'bebidas',
    distanceKm: 0.9,
    price: 3500,
    oldPrice: 4400,
    discount: 20,
    delivery: true,
    pickup: true,
    openNow: true,
    tone: 'blue',
    imageLabel: 'Cola',
    href: '/productos/coca-cola-3l',
  },
  {
    id: 'pan-frances',
    product: 'Pan francés x 6',
    store: 'Delicias',
    categoryId: 'panaderia',
    distanceKm: 1.5,
    price: 2550,
    oldPrice: 3000,
    discount: 15,
    delivery: true,
    pickup: true,
    openNow: true,
    tone: 'orange',
    imageLabel: 'Pan',
    href: '/productos/pan-frances',
  },
];
